spring:
  application:
    name: calvin
  main:
    lazy-initialization: true
    banner-mode: off

http:
  enabled: true

server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

logging:
  pattern:
    console:
  level:
    com.kelseyde.calvin: INFO