spring:
  application:
    name: calvin
  main:
    lazy-initialization: true
    banner-mode: off

http:
  enabled: true

server:
  port: 8084
  servlet:
    context-path: /${spring.application.name}

logging:
  level:
    root: WARN
    com.kelseyde.calvin: DEBUG